# Generated by Django 4.0.7 on 2022-11-08 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetail',
            fields=[
                ('accountNo', models.AutoField(primary_key=True, serialize=False)),
                ('newCreditCustomer', models.BooleanField()),
                ('age', models.IntegerField()),
                ('gender', models.BooleanField()),
                ('education', models.IntegerField()),
                ('maritalStatus', models.IntegerField()),
                ('employmentStatus', models.IntegerField()),
                ('employmentDurationCurrentEmployer', models.CharField(max_length=100)),
                ('incomeTotal', models.IntegerField()),
                ('debtToIncomeRatio', models.FloatField()),
                ('creditScore', models.FloatField()),
                ('noOfPreviousLoansBeforeLoan', models.IntegerField()),
                ('amountOfPreviousLoansBeforeLoan', models.IntegerField()),
                ('noOfPreviousEarlyRepaymentsBeforeLoan', models.IntegerField()),
            ],
        ),
    ]
