# Generated by Django 4.0.7 on 2022-11-10 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankAccounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdetail',
            name='employmentDurationCurrentEmployer',
            field=models.IntegerField(),
        ),
    ]
