# Generated by Django 4.0.7 on 2022-11-10 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankAccounts', '0002_alter_bankdetail_employmentdurationcurrentemployer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdetail',
            name='gender',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bankdetail',
            name='newCreditCustomer',
            field=models.IntegerField(),
        ),
    ]
