# Generated by Django 4.0.7 on 2022-11-13 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankAccounts', '0003_alter_bankdetail_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdetail',
            name='employmentDurationCurrentEmployer',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bankdetail',
            name='newCreditCustomer',
            field=models.CharField(max_length=100),
        ),
    ]
