# Generated by Django 4.0.7 on 2022-11-20 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountNo', models.IntegerField(blank=True)),
                ('amount', models.FloatField(blank=True)),
                ('interest', models.FloatField(blank=True)),
                ('loanDuration', models.IntegerField(blank=True)),
                ('monthlyPayment', models.FloatField(blank=True)),
                ('loanPurpose', models.CharField(blank=True, max_length=100)),
                ('images', models.ImageField(blank=True, null=True, upload_to='images')),
                ('lossGivenDefault', models.FloatField(blank=True)),
                ('default', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(blank=True, max_length=100)),
                ('repayed', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
