# Generated by Django 4.0.7 on 2022-11-13 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanEligibility', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loandetail',
            name='accountNo',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='loandetail',
            name='amount',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='loandetail',
            name='loanDuration',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='loandetail',
            name='loanPurpose',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='loandetail',
            name='monthlyPayment',
            field=models.FloatField(blank=True),
        ),
    ]
